### ISSUE TITLE
test.js 요청사항

### ISSUE THREAD

**Issue by henniyoon** [henniyoon/guild-manager#14]
- db.js에서 sequelize 모듈 가져와서 db 연결 정보 설정하기 (중복 코드 제거)
- 쿼리문 작성 시 orm sequelize 이용하여 작성 ( 길드원 관련일 경우 memberService.js에 정의 후 모듈화 해서 사용 )
- html 작성 시 제일 위에 길드명,  그 아래에 길드원 닉네임만 표시 ( 이 부분 memberService.js에서 findAllMembers() 모듈 사용하면 됨! 기본 오름차순이나 설정 가능하면 좋을 듯!)

**Comment by ChoiEunCheol** [comment]
hard

**Comment by ChoiEunCheol** [comment]
완료
