### ISSUE TITLE
[URGENT] 환경변수 노출 이슈

### ISSUE THREAD

**Issue by imkdw** [henniyoon/guild-manager#47]
### 전역 Config 파일
https://github.com/henniyoon/guild-manager/blob/main/server/config/config.json

DB 및 Nexon API의 키값이 노출되어있습니다.

[.gitignore](https://github.com/henniyoon/guild-manager/blob/main/.gitignore)에 추가하거나 런타임에 주입하도록 변경하시면 좋을듯합니다

![image](https://github.com/henniyoon/guild-manager/assets/79612895/617fa925-3fb1-4872-9bd0-b8f8c116778a)

**Comment by henniyoon** [comment]
gitignore 해주고 해당 파일 히스토리 모두 삭제 후 DB 비밀번호 변경까지 했습니다!
알려주셔서 감사합니다..
